# Use an official Node.js image as a base
FROM node:alpine
RUN apk add chromium

# Set the working directory
WORKDIR '/app'

ENV CHROME_BIN=/usr/bin/chromium-browser

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install Angular CLI globally (optional, if you haven't installed it globally yet)
RUN npm install -g @angular/cli

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# # Expose the port the app runs it does not matter. it always runs to 4200

# EXPOSE 4200

# Start the Angular development server
CMD ["ng", "serve", "--host", "0.0.0.0"]
# CMD ["ng", "serve"]
